### ISSUE TITLE
ConstraintViolationException HTTP status should be configurable

### ISSUE THREAD

**Issue by comrt** [TietoEVRY/quarkus-resteasy-problem#273]
Hello,

some people and companies favor the usage of HTTP-Status Code 422 Unprocessable Entity over 400 Bad Request for validation errors.

I believe it would be convient, if devs could configure the Response Status Code for ConstraintViolationExceptions by a property.

**Comment by lwitkowski** [comment]
Hi @comrt, I get your point and I agree it could be something this extension could support. Are you up for contributing with actual code?

**Comment by comrt** [comment]
hello @lwitkowski i'm working on solution that doesn't generate too much overhead.
I'll come up with a pull request eventually. Thank you for your openness, keep up the good work. 👍

**Comment by comrt** [comment]
Hi @lwitkowski here's my proposal for this feature, may be you can have look at it.
I'm still new to quarkus extensions, maybe there is a better solution. For Unit tests i think i will have to write separate Tests with a TestProfile for different config values. Is there any way to setup the integration test with different config values per test?

https://github.com/comrt/quarkus-resteasy-problem/commit/876feff6968b49ac806b7c302ce06915d29adb42

**Comment by chberger** [comment]
Hi @lwitkowski, first of all thanks for that awesome extension. We also have the same demand as @comrt. Is there any chance that we can configure the ``http status code`` for ``ConstraintViolationException``s soon? Especially, we're also interested in setting a ``422`` for violations which is not supported by ``Response.StatusType`` yet.

**Comment by lwitkowski** [comment]
Hi guys, I might have an idea how to make this work without introducing custom enum (which was main reason we rejected the PR above). I'll try to address this this weekend or early next week.

**Comment by pazkooda** [comment]
@lwitkowski: Do you think we should also register those custom  (I assume `@Injectable`) HTTP status codes by means priority?

Or we should have internal default and if some, single! "reconfiguration bean" exists then we override our extension default?

**Comment by lwitkowski** [comment]
@pazkooda I though about this option briefly, sounds interesting indeed. On the other hand asking devs to implement `Response.StatusType` interface is a bit more cumbersome than asking to provide not just status code but a title (reason phase) as well:
```
quarkus.resteasy.problem.constraint-violation.status=422
quarkus.resteasy.problem.constraint-violation.title=Unprocessable Entity
```

From implementation point of view, an anonymous, dynamic implementation of `Response.StatusType` could work, something similar to [this](https://github.com/resteasy/Resteasy/blob/main/resteasy-core/src/main/java/org/jboss/resteasy/specimpl/AbstractBuiltResponse.java#L134)

**Comment by lwitkowski** [comment]
[v3.1.0](https://github.com/TietoEVRY/quarkus-resteasy-problem/releases/tag/v3.1.0) with this feature is now available in Maven Central, let me guys now how it works for you.

Special thanks to @comrt for creating a feature request and first implementation - it made it clear we need certain refactor before we can implement this properly.
