### ISSUE TITLE
Improve dev experience of creating custom ProblemPostProcessor

### ISSUE THREAD

**Issue by morgenthum** [TietoEVRY/quarkus-resteasy-problem#301]
I want to implement a `ProblemPostProcessor` and need access to the original exception. The `ProblemContext` is passed to the `apply`-Method, but it's fields, including `cause`, is package scoped.

It would be nice to provide getters for the fields in the `ProblemContext` class.

**Comment by mbechto** [comment]
We are in need of this as well, as it would make a lot of nice use cases possible.

Btw. what is the intended way of registering `ProblemPostProcessor`s at runtime?

**Comment by lwitkowski** [comment]
I've slightly changed the title to make the scope of this issue a bit bigger:
- access fields of ProblemContext (addressed by @chberger in #311)
- addressing `what is the intended way of registering ProblemPostProcessors at runtime?` question from @mbechto, which I'm working on right now, stay tuned.

**Comment by lwitkowski** [comment]
@morgenthum @mbechto, happy to report that [v3.1.0](https://github.com/TietoEVRY/quarkus-resteasy-problem/releases/tag/v3.1.0) with this feature is now available in Maven Central, let me guys now how it works for you.

**Comment by mbechto** [comment]
Great news, thanks @lwitkowski! We will test it and report back to you soon.
