### ISSUE TITLE
Exception occurring when encoding the path containing unwise characters (i.e space)

### ISSUE THREAD

**Issue by wolfe111** [TietoEVRY/quarkus-resteasy-problem#358]
**Describe the bug**
The below exception is occurring when there is a space in the path which is not encoded, like `/api/v1/users/Some Space.`

`IllegalArgumentException: Illegal character in path at index 29: /api/v1/users/Some Space\n\tat java.base/java.net.URI.create(URI.java:906)\n\tat com.tietoevry.quarkus.resteasy.problem.postprocessing.ProblemDefaultsProvider.defaultInstance(ProblemDefaultsProvider.java:29)\n\tat com.tietoevry.quarkus.resteasy.problem.postprocessing.ProblemDefaultsProvider.apply(ProblemDefaultsProvider.java:24)\n\tat com.tietoevry.quarkus.resteasy.problem.postprocessing.PostProcessorsRegistry.applyPostProcessing(PostProcessorsRegistry.java:44)\n\tat com.tietoevry.quarkus.resteasy.problem.ExceptionMapperBase.toResponse(ExceptionMapperBase.java:25)\n\tat org.jboss.resteasy.core.ExceptionHandler.executeExceptionMapper(ExceptionHandler.java:139)\n\tat org.jboss.resteasy.core.ExceptionHandler.unwrapException(ExceptionHandler.java:183)\n\tat org.jboss.resteasy.core.ExceptionHandler.handleApplicationException(ExceptionHandler.java:100)\n\tat org.jboss.resteasy.core.ExceptionHandler.handleException(ExceptionHandler.java:344)`

Looking at the code it looks like the `defaultInstance` method in `ProblemDefaultsProvider` turns the path to a URI without any encoding.
`return context.path == null ? null : URI.create(context.path);
`

**To Reproduce**
Use a path which has a space in it for example `/api/v1/users/Some Space`

**Expected behavior**
An exception not to occur and the path gets encoded before it turns to a URI.

**Comment by lwitkowski** [comment]
@wolfe111 I've just released the fix for this as https://github.com/TietoEVRY/quarkus-resteasy-problem/releases/tag/v3.7.0 and https://github.com/TietoEVRY/quarkus-resteasy-problem/releases/tag/v3.9.0 (depending on which Quarkus version is used). Thanks for reporting this bug!
