### ISSUE TITLE
Adapt Maven Central release to Token based credentials

### ISSUE THREAD

**Issue by pazkooda** [TietoEVRY/quarkus-resteasy-problem#381]
Due to e-mail send from Maven Central we should update our credentials to be able to publish artifacts to Central Repository:

> 
> from:	The Central Team <central+announce@sonatype.com>
> reply-to:	central-publishers@sonatype.com
> to:	...
> date:	11 Jun 2024, 18:00
> subject:	Maven Central account migration
>
> Dear Maven Central publisher,
> 
> We are making changes to the OSSRH authentication backend. For most users this should be a transparent process, and you should be able to continue to use your existing username and password to connect the Nexus UI. In case you need to update your password, please [follow our documentation](https://u21795309.ct.sendgrid.net/ls/click?upn=u001.cdbupahfLeeV0JrmnGgqhiqfh8Qc-2Bz8uDGMwn-2BLd346s20we4XN3BPxFyn1Wq0GaaIplVfDqOINU8kVpcJu0l4HEn8wbwt3LxWXjAj8v465XLAbYfqJZNQGKDLiKFF8shWrv_mxvAfXR8VQ3GYuKPz7Omfk5rT0IWPC6XW4-2BO27MEiV6lrCbGi5FZ4O-2FpaFS3sheL5-2BN7-2FtARLfLgDrEEQiKaxcaxJn1pTL1soODD5lTodeTQVg7CR-2B-2F9fn1NPemnAvkFJhJTOftYQXXSC8W2ZwL1ZiCQPuklCe9wT5Y2vwT5mL4nI4E9u1BuW7-2Fr-2B4AR4AfMyYNWJeUEEAI926o5eAKBSz5QBd-2BeMPx2KjVnFLq95j99Eq25Y8abfyEx7my2NJw6GSWX3iV-2BynhszWSICQo9Yx3SeVOGru9A8Eoo2ZLDQi1jW2C-2BIrkG50jBJx4A-2BwwaWJWzxdsvoLPTExCZkT1rwvunoYWriPh9X6HpyYxy9Pm67nhZ-2Fdi-2Bq5WsI-2FdmPaaU-2BHxXe5ra6m-2BxXX39N1GS36f0LxFpjRnyJbmzIOwACJJx6i4p99u7g6Lsl6n-2BeSk-2BQzTDEfaS9vxGkKINIbm3VjJjX1l4IsCq14E-2FgD-2F01jXEroJg-2FCk8LIZYvW-2FFR-2FCQUWCA-2FXgIeCuLwfmP7y2TdlnfPI-2FcVxppCXuSpSWPerxd4fjZ2ekx0N-2B-2FE61nOKPyVgj-2BsAPuOyqhXrb5vB0IlxaQIcnp9mu8pka9z8FAt8l-2Bf8K4SmkEHVRwEqq4ZdNg-2FnzA3W9s-2BLG2XVuDUh7qmPTTAIyULLLvTutvs5u6k5mg06KFGwtn57soD5JV-2F9rIVYSTUrCZrhrU0pQ-2BhoMcq7oqwsU9CD-2FmDD2D2aj6yFnrPWZapwvIS9VoWB04GR7knjk6x1K6x6ExwqQINzkQqL71NcyKPAA7b3gvOWU-2B9Iju31dCAEdKQuZXk6bMjKKD1kHHTYCPTa0C-2F7VS7pRJKjRy2Jow8rd8yAhB9ba-2FS8o4-2F7xCZu9doHP9ekmCr0y6dcWKKIFxSyDVOTBKrzEbhHE1R9EntFtt5uKJtNoI0jHJ8aNo-2B1fozyeIkUpJZ-2FfKBihFjONHpghU-2Bsv5Ag6pSwcFirtaFf8dBheRYQOJ0NUV4fpZZrdZK6hoopMruX9n).
> 
> To configure a publisher’s plugin authentication you would need to update your plugin settings to use [a user token](https://u21795309.ct.sendgrid.net/ls/click?upn=u001.cdbupahfLeeV0JrmnGgqhiqfh8Qc-2Bz8uDGMwn-2BLd347g0tp5qqliMjnSbao6WwprVLD9osT0EVrc2A0tPevF3w-3D-3DOX10_mxvAfXR8VQ3GYuKPz7Omfk5rT0IWPC6XW4-2BO27MEiV6lrCbGi5FZ4O-2FpaFS3sheL5-2BN7-2FtARLfLgDrEEQiKaxcaxJn1pTL1soODD5lTodeTQVg7CR-2B-2F9fn1NPemnAvkFJhJTOftYQXXSC8W2ZwL1ZiCQPuklCe9wT5Y2vwT5mL4nI4E9u1BuW7-2Fr-2B4AR4AfMyYNWJeUEEAI926o5eAKBSz5QBd-2BeMPx2KjVnFLq95j99Eq25Y8abfyEx7my2NJw6GSWX3iV-2BynhszWSICQo9Yx3SeVOGru9A8Eoo2ZLDQi1jW2C-2BIrkG50jBJx4A-2BwwaWJWzxdsvoLPTExCZkT1rwvunoYWriPh9X6HpyYxy9Pm67nhZ-2Fdi-2Bq5WsI-2FdmPaaU-2BHxXe5ra6m-2BxXX39N1GS36f0LxFpjRnyJbmzIOwACJJx6i4p99u7g6Lsl6n-2BeSk-2BQzTDEfaS9vxGkKINIbm3VjJjX1l4IsCq14E-2FgD-2F01jXEroJg-2FCk8LIZYvW-2FFR-2FCQUWCA-2FXgIeCuLwfmP7y2TdlnfPI-2FcVxppCXuSpSWPerxd4fjZ2ekx0N-2B-2FE61nOKPyVgj-2BsAPuOyqhXrb5vB0IlxaQIcnp9mu8pka9z8FAt8l-2Bf8K4SmkEHVRwEqq4ZdNg-2FnzA3W9s-2BLG2XVuDUh7qmPTTAIyULLLvTutvs5u6k5mg06KFGwtn57soD5JV-2F9rIVYSTUrCZrhrU0pQ-2BhoMcq7oqwsU9CD-2FmDD2D2aj6yFnrPWZapwvIS9VoWB04GR7knjk6x1K6x6ExwqQINzkQqAEpftGjkRXEZ6B4Wj8GiS55rVmX1EUqdVMQhU4D89p9w-2FGNDlfmt6B4eXe2Z9PmIjEGjQ7FhkuxI-2F7wdf2dOyZwuK0VhiarD9qGXQtfkEnfJZtOsTDk2CRWlTqEf4-2BvGSPs8cVsdF6zbFW0xCk3mYZ1CUEmZfnLXDmoNto32t8ll5IHsb3yPNcx4s9jXI6y44a3QRmnz1fHfqq2J-2FcZrLBku79PiWtFIWLkajLirI9a) instead of the Nexus UI username and password login.
> 
> For more information about publishing to legacy OSSRH please consult our documentation at [https://central.sonatype.org/register/legacy/](https://u21795309.ct.sendgrid.net/ls/click?upn=u001.cdbupahfLeeV0JrmnGgqhiqfh8Qc-2Bz8uDGMwn-2BLd346ivUzum4Xd73zPSejBlFv-2F0bAAz7vmZ03FTCcnlHq6Qg-3D-3DZxGK_mxvAfXR8VQ3GYuKPz7Omfk5rT0IWPC6XW4-2BO27MEiV6lrCbGi5FZ4O-2FpaFS3sheL5-2BN7-2FtARLfLgDrEEQiKaxcaxJn1pTL1soODD5lTodeTQVg7CR-2B-2F9fn1NPemnAvkFJhJTOftYQXXSC8W2ZwL1ZiCQPuklCe9wT5Y2vwT5mL4nI4E9u1BuW7-2Fr-2B4AR4AfMyYNWJeUEEAI926o5eAKBSz5QBd-2BeMPx2KjVnFLq95j99Eq25Y8abfyEx7my2NJw6GSWX3iV-2BynhszWSICQo9Yx3SeVOGru9A8Eoo2ZLDQi1jW2C-2BIrkG50jBJx4A-2BwwaWJWzxdsvoLPTExCZkT1rwvunoYWriPh9X6HpyYxy9Pm67nhZ-2Fdi-2Bq5WsI-2FdmPaaU-2BHxXe5ra6m-2BxXX39N1GS36f0LxFpjRnyJbmzIOwACJJx6i4p99u7g6Lsl6n-2BeSk-2BQzTDEfaS9vxGkKINIbm3VjJjX1l4IsCq14E-2FgD-2F01jXEroJg-2FCk8LIZYvW-2FFR-2FCQUWCA-2FXgIeCuLwfmP7y2TdlnfPI-2FcVxppCXuSpSWPerxd4fjZ2ekx0N-2B-2FE61nOKPyVgj-2BsAPuOyqhXrb5vB0IlxaQIcnp9mu8pka9z8FAt8l-2Bf8K4SmkEHVRwEqq4ZdNg-2FnzA3W9s-2BLG2XVuDUh7qmPTTAIyULLLvTutvs5u6k5mg06KFGwtn57soD5JV-2F9rIVYSTUrCZrhrU0pQ-2BhoMcq7oqwsU9CD-2FmDD2D2aj6yFnrPWZapwvIS9VoWB04GR7knjk6x1K6x6ExwqQINzkQqP-2B4gEV5VE4gEiS6zvEvi05ZzqT9CizWoPxeUfoBP5BA3fe2-2FalLbzaPBt-2Fdu-2BGzqjIS7olegViGL-2FBb1J4Tlx085t1yE3fgrfBFjY-2Fk2d6HgrTVin-2BLop51pmQ3zOIgN9tJszJateiriUYsoZYsfLvkCuKbpvYEYPAzx4-2FbQNONMRdMu8DWZYc1R2XsUAqo1FX0OTjjPdPfNRyilkfw7MXSmaoTOs0Y1bJxZwc-2FDZTl)
> 
> 
> Thank you,
> The Central Team

If I correctly understood simple change of `secrets.NEXUS_PASSWORD` to `secrets.NEXUS_TOKEN` (to be generated and set in GH) in this line: https://github.com/TietoEVRY/quarkus-resteasy-problem/blob/358f9a7491b27bec4908b6db0d1cb577b8614c8c/.github/workflows/publish.yml#L24 should do the job.

**Comment by lwitkowski** [comment]
Seems to be working fine for publishing snapshot:
![image](https://github.com/TietoEVRY/quarkus-resteasy-problem/assets/38762002/b0dfa0a3-c7bc-4ca9-81ee-c560b810ebe9)

I had to extend the gpg signature key as well, which turned out to be expired 2 months ago.
Thanks @pazkooda
