### ISSUE TITLE
Add mapper for `io.quarkus.rest.data.panache.RestDataPanacheException`

### ISSUE THREAD

**Issue by lwitkowski** [TietoEVRY/quarkus-resteasy-problem#84]
Not sure then this exception is thrown exactly (to be investigated as part of this task), but there are multiple custom exception mappers:
```
io.quarkus.spring.data.rest.runtime.RestDataPanacheExceptionMapper implements ExceptionMapper<RestDataPanacheException>
io.quarkus.hibernate.orm.rest.data.panache.runtime.RestDataPanacheExceptionMapper implements ExceptionMapper<RestDataPanacheException>
io.quarkus.mongodb.rest.data.panache.runtime.RestDataPanacheExceptionMapper implements ExceptionMapper<RestDataPanacheException>
```
which we should override (ours should have higher priority than any of the above) if panache (or one of related extensions) is in classpath, and turn this exception into nice problem.

**Comment by SivaTharun** [comment]
@lwitkowski i am a newbie to open source contribution, can i start working on this issue.

**Comment by lwitkowski** [comment]
Nobody asks for it, nobody votes for it, closing.
